# Generated by Django 3.2.4 on 2021-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('vehicleType', models.CharField(blank=None, choices=[('two wheeler', 'two wheeler'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], max_length=25, null=True)),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=20)),
                ('workingHours', models.TextField(max_length=100)),
                ('panCardNumber', models.CharField(max_length=20)),
                ('uploadPanCard', models.ImageField(upload_to='images')),
                ('nameAsOnPandcard', models.CharField(max_length=20)),
                ('aadarNumber', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('fatherName', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=10)),
                ('address2', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('licenseNumber', models.CharField(max_length=10)),
                ('dlexpiry', models.DateField()),
                ('dlUploadFront', models.ImageField(upload_to='images')),
                ('dlUploadBack', models.ImageField(upload_to='images')),
                ('vehicleNumber', models.CharField(max_length=15)),
                ('vehicleMake', models.CharField(max_length=10)),
                ('insuranceNumber', models.CharField(max_length=20)),
                ('rcBookUpload', models.ImageField(upload_to='images')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('address', models.TextField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('certificate_or_license', models.CharField(max_length=50)),
                ('store_charge', models.CharField(max_length=50)),
                ('store_manager_name', models.CharField(max_length=50)),
                ('store_manager_email', models.CharField(max_length=50)),
                ('store_manager_phone', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
